// Trail Companion — field guide data.
// Shared by the browser app AND scripts/build-embeddings.mjs (Node).
// Because CLIP is zero-shot, adding a species is just adding a line here
// (then re-running `npm run embeddings`) — no retraining required.

export const CATEGORIES = {
  bird:   { label: 'Bird',            emoji: '🐦', noun: 'bird' },
  tree:   { label: 'Tree & Leaf',     emoji: '🍁', noun: 'tree' },
  flower: { label: 'Flower',          emoji: '🌼', noun: 'flower' },
  fungi:  { label: 'Fungi',           emoji: '🍄', noun: 'mushroom' },
  insect: { label: 'Bugs & Critters', emoji: '🐞', noun: 'insect' },
  none:   { label: 'Not nature',      emoji: '📵', noun: 'thing' },
};

// tags: used by Trail Bingo ("something red", "something yellow", ...)
export const SPECIES = [
  // ── Birds ────────────────────────────────────────────────────────────
  { id: 'northern-cardinal', name: 'Northern Cardinal', sci: 'Cardinalis cardinalis', cat: 'bird', tags: ['red'],
    fact: 'Males are brilliant red; females are tan with red accents. Both sexes sing.',
    next: 'Listen for a loud, clear "birdy-birdy-birdy" whistle from dense shrubs.' },
  { id: 'american-robin', name: 'American Robin', sci: 'Turdus migratorius', cat: 'bird', tags: ['red'],
    fact: 'Robins hunt earthworms by sight, tilting their heads to scan the lawn.',
    next: 'Watch an open lawn for the run–stop–tilt–grab hunting pattern.' },
  { id: 'blue-jay', name: 'Blue Jay', sci: 'Cyanocitta cristata', cat: 'bird', tags: ['blue'],
    fact: 'Blue Jays can mimic the scream of a Red-shouldered Hawk.',
    next: 'Look under oaks — jays cache thousands of acorns each autumn.' },
  { id: 'black-capped-chickadee', name: 'Black-capped Chickadee', sci: 'Poecile atricapillus', cat: 'bird', tags: [],
    fact: 'The more "dee"s in its chick-a-dee call, the bigger the threat it has spotted.',
    next: 'Stand still near a conifer and count the "dee"s in the calls.' },
  { id: 'house-sparrow', name: 'House Sparrow', sci: 'Passer domesticus', cat: 'bird', tags: [],
    fact: 'One of the most widespread birds on Earth, living alongside people on every inhabited continent.',
    next: 'Find a dusty patch — sparrows take dust baths to clean their feathers.' },
  { id: 'european-robin', name: 'European Robin', sci: 'Erithacus rubecula', cat: 'bird', tags: ['red'],
    fact: 'Robins sing through autumn and winter to defend feeding territories.',
    next: 'Turn some soil in a garden — robins often follow gardeners for worms.' },
  { id: 'great-tit', name: 'Great Tit', sci: 'Parus major', cat: 'bird', tags: ['yellow'],
    fact: 'The width of a male\'s black chest stripe signals his status.',
    next: 'Listen for a two-note "tea-cher, tea-cher" song.' },
  { id: 'common-myna', name: 'Common Myna', sci: 'Acridotheres tristis', cat: 'bird', tags: ['yellow'],
    fact: 'Mynas are superb mimics and often pair for life.',
    next: 'Watch for the white wing patches flashing when it takes off.' },
  { id: 'red-vented-bulbul', name: 'Red-vented Bulbul', sci: 'Pycnonotus cafer', cat: 'bird', tags: ['red'],
    fact: 'Named for the crimson patch under its tail.',
    next: 'Check fruiting trees and bushes — bulbuls love berries.' },
  { id: 'indian-peafowl', name: 'Indian Peafowl', sci: 'Pavo cristatus', cat: 'bird', tags: ['blue'],
    fact: 'A peacock\'s "tail" is actually elongated upper-tail covert feathers.',
    next: 'Listen at dusk for the loud "may-awe" call from tree roosts.' },
  { id: 'house-crow', name: 'House Crow', sci: 'Corvus splendens', cat: 'bird', tags: [],
    fact: 'Crows recognise individual human faces and remember them for years.',
    next: 'Watch a group of crows — they often hold noisy "meetings".' },
  { id: 'rock-pigeon', name: 'Rock Pigeon', sci: 'Columba livia', cat: 'bird', tags: [],
    fact: 'Pigeons can navigate home from hundreds of kilometres away.',
    next: 'Notice the iridescent green-purple sheen on the neck in sunlight.' },
  { id: 'mallard', name: 'Mallard Duck', sci: 'Anas platyrhynchos', cat: 'bird', tags: ['water'],
    fact: 'Only female mallards make the classic loud "quack".',
    next: 'Find a pond and look for the blue wing patch (speculum).' },
  { id: 'great-blue-heron', name: 'Great Blue Heron', sci: 'Ardea herodias', cat: 'bird', tags: ['water', 'blue'],
    fact: 'Herons stand motionless for minutes, then strike fish in a split second.',
    next: 'Scan still shallows at the water\'s edge — be patient and quiet.' },
  { id: 'common-kingfisher', name: 'Common Kingfisher', sci: 'Alcedo atthis', cat: 'bird', tags: ['water', 'blue'],
    fact: 'Kingfishers dive into water at up to 40 km/h with eyes protected by a membrane.',
    next: 'Follow a slow stream and listen for a sharp, high whistle.' },
  { id: 'rose-ringed-parakeet', name: 'Rose-ringed Parakeet', sci: 'Psittacula krameri', cat: 'bird', tags: ['green'],
    fact: 'Feral flocks now thrive in cities from London to Tokyo.',
    next: 'Listen for screeching flocks flying to roost at sunset.' },
  { id: 'barn-swallow', name: 'Barn Swallow', sci: 'Hirundo rustica', cat: 'bird', tags: ['blue'],
    fact: 'Barn Swallows catch insects mid-air and migrate between continents.',
    next: 'Watch low over fields or water for fast, swooping flight.' },
  { id: 'bald-eagle', name: 'Bald Eagle', sci: 'Haliaeetus leucocephalus', cat: 'bird', tags: ['water'],
    fact: 'Eagle nests can weigh over a tonne after years of additions.',
    next: 'Scan tall trees near large lakes and rivers.' },

  // ── Trees & leaves ───────────────────────────────────────────────────
  { id: 'sugar-maple', name: 'Sugar Maple', sci: 'Acer saccharum', cat: 'tree', tags: ['fall', 'yellow', 'red'],
    fact: 'Its sap is boiled down ~40:1 to make maple syrup.',
    next: 'Find the winged "helicopter" seeds and drop one to watch it spin.' },
  { id: 'red-maple', name: 'Red Maple', sci: 'Acer rubrum', cat: 'tree', tags: ['fall', 'red'],
    fact: 'Red maples have something red in every season: buds, flowers, stems and fall leaves.',
    next: 'Check the leaf edge — red maple leaves have sharp, toothed lobes.' },
  { id: 'japanese-maple', name: 'Japanese Maple', sci: 'Acer palmatum', cat: 'tree', tags: ['fall', 'red'],
    fact: 'Cultivated in Japan for centuries, with over 1,000 named varieties.',
    next: 'Count the lobes — usually 5 to 9, like an open hand.' },
  { id: 'red-oak', name: 'Northern Red Oak', sci: 'Quercus rubra', cat: 'tree', tags: ['fall', 'red'],
    fact: 'Red oak leaves have pointed, bristle-tipped lobes.',
    next: 'Look for acorns with flat, saucer-like caps.' },
  { id: 'english-oak', name: 'English Oak', sci: 'Quercus robur', cat: 'tree', tags: ['fall'],
    fact: 'A single mature oak can support over 2,000 species of wildlife.',
    next: 'Look for round, rounded-lobe leaves and acorns on long stalks.' },
  { id: 'paper-birch', name: 'Paper Birch', sci: 'Betula papyrifera', cat: 'tree', tags: ['fall', 'yellow'],
    fact: 'Its white bark peels in thin papery layers and was used for canoes.',
    next: 'Look at the bark — but don\'t peel it from living trees.' },
  { id: 'ginkgo', name: 'Ginkgo', sci: 'Ginkgo biloba', cat: 'tree', tags: ['fall', 'yellow'],
    fact: 'A living fossil — ginkgo has barely changed in 200 million years.',
    next: 'Find the fan-shaped leaves; in autumn they all drop within days.' },
  { id: 'pine', name: 'Pine', sci: 'Pinus spp.', cat: 'tree', tags: ['evergreen'],
    fact: 'You can often identify a pine by counting needles per bundle (2, 3 or 5).',
    next: 'Pick up a fallen bundle of needles and count them.' },
  { id: 'spruce', name: 'Spruce', sci: 'Picea spp.', cat: 'tree', tags: ['evergreen'],
    fact: 'Spruce needles are square in cross-section — you can roll one between your fingers.',
    next: 'Roll a needle between your fingers: spruce rolls, fir doesn\'t.' },
  { id: 'weeping-willow', name: 'Weeping Willow', sci: 'Salix babylonica', cat: 'tree', tags: ['water'],
    fact: 'Willow bark contains salicin, the natural precursor to aspirin.',
    next: 'Willows love water — follow one to a nearby pond or stream.' },
  { id: 'london-plane', name: 'London Plane / Sycamore', sci: 'Platanus spp.', cat: 'tree', tags: ['fall'],
    fact: 'Its camouflage-patterned bark flakes off, helping it survive city pollution.',
    next: 'Look for spiky seed balls hanging like ornaments.' },
  { id: 'horse-chestnut', name: 'Horse Chestnut', sci: 'Aesculus hippocastanum', cat: 'tree', tags: ['fall'],
    fact: 'Its shiny seeds ("conkers") are toxic to eat but great for the game of conkers.',
    next: 'Look for spiky green husks on the ground in autumn.' },
  { id: 'banyan', name: 'Banyan', sci: 'Ficus benghalensis', cat: 'tree', tags: [],
    fact: 'Banyans grow aerial roots that become new trunks — one tree can cover hectares.',
    next: 'Walk under it and count the hanging aerial roots.' },
  { id: 'peepal', name: 'Peepal (Sacred Fig)', sci: 'Ficus religiosa', cat: 'tree', tags: [],
    fact: 'Recognisable by heart-shaped leaves with a long, dripping tip.',
    next: 'Stand under it on a breezy day — the leaves flutter and rustle constantly.' },
  { id: 'neem', name: 'Neem', sci: 'Azadirachta indica', cat: 'tree', tags: [],
    fact: 'Neem has been used for centuries as a natural pesticide and in traditional medicine.',
    next: 'Look for leaflets with saw-toothed edges arranged along a central stem.' },
  { id: 'coconut-palm', name: 'Coconut Palm', sci: 'Cocos nucifera', cat: 'tree', tags: [],
    fact: 'Coconuts can float across oceans and still sprout on a new beach.',
    next: 'Never stand directly under a fruiting palm on a windy day!' },
  { id: 'eucalyptus', name: 'Eucalyptus', sci: 'Eucalyptus spp.', cat: 'tree', tags: [],
    fact: 'Crush a leaf — the strong scent comes from eucalyptol oil.',
    next: 'Gently crush a fallen leaf and smell it.' },

  // ── Flowers ──────────────────────────────────────────────────────────
  { id: 'sunflower', name: 'Sunflower', sci: 'Helianthus annuus', cat: 'flower', tags: ['yellow'],
    fact: 'Young sunflowers track the sun east to west; mature ones face east.',
    next: 'Count the seed spirals — they follow Fibonacci numbers.' },
  { id: 'daisy', name: 'Common Daisy', sci: 'Bellis perennis', cat: 'flower', tags: ['yellow'],
    fact: 'Each "flower" is actually hundreds of tiny florets.',
    next: 'Find a daisy at dusk — they close their petals at night.' },
  { id: 'dandelion', name: 'Dandelion', sci: 'Taraxacum officinale', cat: 'flower', tags: ['yellow'],
    fact: 'Each seed head can carry ~150 seeds that drift kilometres on the wind.',
    next: 'Find a seed head and see how far the seeds travel in the breeze.' },
  { id: 'rose', name: 'Rose', sci: 'Rosa spp.', cat: 'flower', tags: ['red'],
    fact: 'Rose hips — the fruit left after flowering — are rich in vitamin C.',
    next: 'Look for red-orange rose hips on bushes in autumn.' },
  { id: 'hibiscus', name: 'Hibiscus', sci: 'Hibiscus rosa-sinensis', cat: 'flower', tags: ['red'],
    fact: 'Most hibiscus flowers last only a single day.',
    next: 'Check the long central column — that\'s the fused stamens and pistil.' },
  { id: 'marigold', name: 'Marigold', sci: 'Tagetes spp.', cat: 'flower', tags: ['yellow'],
    fact: 'Gardeners plant marigolds to help deter some soil pests.',
    next: 'Gently rub a leaf and notice its strong, spicy scent.' },
  { id: 'lotus', name: 'Lotus', sci: 'Nelumbo nucifera', cat: 'flower', tags: ['water'],
    fact: 'Lotus leaves are self-cleaning — water beads up and rolls off with dirt.',
    next: 'Watch water droplets roll across a lotus leaf.' },
  { id: 'coneflower', name: 'Purple Coneflower', sci: 'Echinacea purpurea', cat: 'flower', tags: [],
    fact: 'Goldfinches feast on coneflower seeds in late summer and fall.',
    next: 'Watch the cone for bees and butterflies feeding.' },
  { id: 'black-eyed-susan', name: 'Black-eyed Susan', sci: 'Rudbeckia hirta', cat: 'flower', tags: ['yellow'],
    fact: 'A tough native wildflower of North American prairies.',
    next: 'Feel the leaves — they\'re rough and hairy.' },
  { id: 'lavender', name: 'Lavender', sci: 'Lavandula spp.', cat: 'flower', tags: [],
    fact: 'A favourite of bees — a single lavender patch can buzz all day.',
    next: 'Stand near it for one minute and count the bees.' },
  { id: 'bougainvillea', name: 'Bougainvillea', sci: 'Bougainvillea spp.', cat: 'flower', tags: ['red'],
    fact: 'The colourful "petals" are actually bracts; the real flowers are tiny and white.',
    next: 'Look in the middle of the bracts for the tiny white true flowers.' },
  { id: 'frangipani', name: 'Frangipani', sci: 'Plumeria spp.', cat: 'flower', tags: ['yellow'],
    fact: 'Frangipani is most fragrant at night to attract sphinx moths.',
    next: 'Come back at dusk and smell the difference.' },
  { id: 'goldenrod', name: 'Goldenrod', sci: 'Solidago spp.', cat: 'flower', tags: ['yellow', 'fall'],
    fact: 'Often blamed for hay fever, but its pollen is heavy and insect-carried.',
    next: 'Look for round galls on the stems — insect larvae live inside.' },
  { id: 'aster', name: 'New England Aster', sci: 'Symphyotrichum novae-angliae', cat: 'flower', tags: ['fall'],
    fact: 'Asters are a vital late-season nectar source for migrating monarchs.',
    next: 'Watch asters on a sunny fall afternoon for butterflies.' },
  { id: 'clover', name: 'Clover', sci: 'Trifolium spp.', cat: 'flower', tags: [],
    fact: 'Clover pulls nitrogen from the air and enriches the soil.',
    next: 'Search the patch for a four-leaf clover (about 1 in 5,000).' },

  // ── Fungi ────────────────────────────────────────────────────────────
  { id: 'fly-agaric', name: 'Fly Agaric', sci: 'Amanita muscaria', cat: 'fungi', tags: ['red'], toxic: true,
    fact: 'The iconic red-and-white toadstool. It is poisonous.',
    next: 'Look nearby for birch or pine — it partners with their roots.' },
  { id: 'death-cap', name: 'Death Cap', sci: 'Amanita phalloides', cat: 'fungi', tags: [], toxic: true,
    fact: 'Responsible for most fatal mushroom poisonings worldwide. Do not touch or taste.',
    next: 'Note the location and wash your hands if you touched anything.' },
  { id: 'chanterelle', name: 'Chanterelle', sci: 'Cantharellus spp.', cat: 'fungi', tags: ['yellow'],
    fact: 'Has blunt, forking ridges instead of true gills. Toxic look-alikes exist.',
    next: 'Look at the underside: ridges that run down the stem.' },
  { id: 'turkey-tail', name: 'Turkey Tail', sci: 'Trametes versicolor', cat: 'fungi', tags: ['fall'],
    fact: 'Its banded colours resemble a turkey\'s tail fan.',
    next: 'Check fallen logs — turkey tail recycles dead wood.' },
  { id: 'oyster-mushroom', name: 'Oyster Mushroom', sci: 'Pleurotus ostreatus', cat: 'fungi', tags: [],
    fact: 'Oyster mushrooms can trap and digest tiny nematode worms.',
    next: 'Look for shelf-like clusters on dead hardwood trees.' },
  { id: 'puffball', name: 'Puffball', sci: 'Lycoperdon spp.', cat: 'fungi', tags: [],
    fact: 'Mature puffballs release clouds of spores when raindrops hit them.',
    next: 'Look for small white balls on lawns and woodland floors.' },
  { id: 'shaggy-ink-cap', name: 'Shaggy Ink Cap', sci: 'Coprinus comatus', cat: 'fungi', tags: [],
    fact: 'It digests itself into black "ink" within hours of maturing.',
    next: 'Check lawns and roadsides after autumn rain.' },
  { id: 'artists-conk', name: 'Bracket Fungus', sci: 'Ganoderma spp.', cat: 'fungi', tags: [],
    fact: 'Some bracket fungi live for decades, adding a new layer each year.',
    next: 'Look up the trunk of old or dead trees for shelf fungi.' },

  // ── Bugs & critters ──────────────────────────────────────────────────
  { id: 'monarch', name: 'Monarch Butterfly', sci: 'Danaus plexippus', cat: 'insect', tags: ['fall'],
    fact: 'Eastern monarchs migrate up to 4,800 km to overwinter in Mexico.',
    next: 'Look on milkweed plants for striped caterpillars.' },
  { id: 'painted-lady', name: 'Painted Lady', sci: 'Vanessa cardui', cat: 'insect', tags: [],
    fact: 'The most widespread butterfly on Earth, found on every continent but Antarctica and South America.',
    next: 'Watch thistles and sunny flower beds.' },
  { id: 'honey-bee', name: 'Honey Bee', sci: 'Apis mellifera', cat: 'insect', tags: ['yellow'],
    fact: 'Bees "waggle dance" to tell hive-mates where flowers are.',
    next: 'Follow a bee from flower to flower — they stick to one type per trip.' },
  { id: 'bumblebee', name: 'Bumblebee', sci: 'Bombus spp.', cat: 'insect', tags: ['yellow'],
    fact: 'Bumblebees "buzz pollinate", vibrating flowers to shake out pollen.',
    next: 'Listen for the buzz change when one lands on a flower.' },
  { id: 'ladybird', name: 'Ladybug (Ladybird)', sci: 'Coccinellidae', cat: 'insect', tags: ['red'],
    fact: 'A single ladybug can eat 5,000 aphids in its lifetime.',
    next: 'Check the undersides of leaves for aphids — ladybugs will be close.' },
  { id: 'dragonfly', name: 'Dragonfly', sci: 'Anisoptera', cat: 'insect', tags: ['water'],
    fact: 'Dragonflies catch over 90% of the prey they chase.',
    next: 'Sit by a pond — dragonflies return to the same perch again and again.' },
  { id: 'damselfly', name: 'Damselfly', sci: 'Zygoptera', cat: 'insect', tags: ['water', 'blue'],
    fact: 'Unlike dragonflies, damselflies fold their wings along their body at rest.',
    next: 'Look in reeds at the water\'s edge.' },
  { id: 'praying-mantis', name: 'Praying Mantis', sci: 'Mantodea', cat: 'insect', tags: ['green'],
    fact: 'Mantises can turn their heads 180° to scan for prey.',
    next: 'Search tall grass and shrubs in late summer — they\'re masters of camouflage.' },
  { id: 'grasshopper', name: 'Grasshopper', sci: 'Caelifera', cat: 'insect', tags: ['green'],
    fact: 'Grasshoppers "hear" with organs on their abdomen.',
    next: 'Walk slowly through a meadow and watch them leap ahead of you.' },
  { id: 'garden-spider', name: 'Orb-weaver Spider', sci: 'Araneidae', cat: 'insect', tags: ['yellow'],
    fact: 'Many orb-weavers eat and rebuild their web every single day.',
    next: 'Look for webs at dawn when dew makes them sparkle.' },
  { id: 'snail', name: 'Garden Snail', sci: 'Cornu aspersum', cat: 'insect', tags: [],
    fact: 'Snails have thousands of microscopic teeth on a ribbon-like radula.',
    next: 'Go out after rain — snails are most active when it\'s damp.' },
  { id: 'caterpillar', name: 'Caterpillar', sci: 'Lepidoptera larva', cat: 'insect', tags: ['green'],
    fact: 'A caterpillar can grow ~1,000× in mass before pupating.',
    next: 'Look for chewed leaf edges — the caterpillar is usually nearby.' },
];

// "Not nature" negatives — lets the app gently say "go outside!"
export const NEGATIVES = [
  { id: 'neg-person', name: 'A person', cat: 'none', prompts: ['a selfie of a person', 'a photo of a person\'s face'] },
  { id: 'neg-screen', name: 'A screen', cat: 'none', prompts: ['a screenshot of a computer screen', 'a photo of a laptop or phone screen'] },
  { id: 'neg-indoor', name: 'Indoors', cat: 'none', prompts: ['a photo of an indoor room with furniture', 'a photo of an office desk'] },
  { id: 'neg-street', name: 'Street & buildings', cat: 'none', prompts: ['a photo of cars on a city street', 'a photo of a building'] },
  { id: 'neg-food', name: 'Food', cat: 'none', prompts: ['a photo of food on a plate'] },
  { id: 'neg-pet', name: 'A pet', cat: 'none', prompts: ['a photo of a pet dog', 'a photo of a pet cat'] },
];

const TEMPLATES = {
  bird:   n => [`a photo of a ${n}, a type of bird.`, `a close-up photo of a ${n} bird.`, `a wildlife photo of a ${n}.`],
  tree:   n => [`a photo of a ${n} leaf.`, `a photo of a ${n} tree.`, `a photo of the leaves of a ${n}, a type of tree.`],
  flower: n => [`a photo of a ${n}, a type of flower.`, `a close-up photo of ${n} flowers.`],
  fungi:  n => [`a photo of a ${n}, a type of mushroom.`, `a photo of ${n} fungus growing outdoors.`],
  insect: n => [`a photo of a ${n}.`, `a macro photo of a ${n}, a type of insect or bug.`],
};

/** Text prompts used to build a CLIP text embedding for a label (prompt ensembling). */
export function promptsFor(s) {
  if (s.prompts) return s.prompts;
  const n = s.name.replace(/\s*\(.*?\)\s*/g, ' ').replace(/\s*\/.*$/, '').trim();
  return (TEMPLATES[s.cat] || TEMPLATES.insect)(n);
}

export const ALL_LABELS = [...SPECIES, ...NEGATIVES];
